/* 
 * AspApiSample.Web.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing User
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserTests
    {
        // TODO uncomment below to declare an instance variable for User
        //private User instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of User
            //instance = new User();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of User
        /// </summary>
        [Test]
        public void UserInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" User
            //Assert.IsInstanceOfType<User> (instance, "variable 'instance' is a User");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Test]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }
        /// <summary>
        /// Test the property 'NormalizedUserName'
        /// </summary>
        [Test]
        public void NormalizedUserNameTest()
        {
            // TODO unit test for the property 'NormalizedUserName'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'NormalizedEmail'
        /// </summary>
        [Test]
        public void NormalizedEmailTest()
        {
            // TODO unit test for the property 'NormalizedEmail'
        }
        /// <summary>
        /// Test the property 'EmailConfirmed'
        /// </summary>
        [Test]
        public void EmailConfirmedTest()
        {
            // TODO unit test for the property 'EmailConfirmed'
        }
        /// <summary>
        /// Test the property 'PasswordHash'
        /// </summary>
        [Test]
        public void PasswordHashTest()
        {
            // TODO unit test for the property 'PasswordHash'
        }
        /// <summary>
        /// Test the property 'SecurityStamp'
        /// </summary>
        [Test]
        public void SecurityStampTest()
        {
            // TODO unit test for the property 'SecurityStamp'
        }
        /// <summary>
        /// Test the property 'ConcurrencyStamp'
        /// </summary>
        [Test]
        public void ConcurrencyStampTest()
        {
            // TODO unit test for the property 'ConcurrencyStamp'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'PhoneNumberConfirmed'
        /// </summary>
        [Test]
        public void PhoneNumberConfirmedTest()
        {
            // TODO unit test for the property 'PhoneNumberConfirmed'
        }
        /// <summary>
        /// Test the property 'TwoFactorEnabled'
        /// </summary>
        [Test]
        public void TwoFactorEnabledTest()
        {
            // TODO unit test for the property 'TwoFactorEnabled'
        }
        /// <summary>
        /// Test the property 'LockoutEnd'
        /// </summary>
        [Test]
        public void LockoutEndTest()
        {
            // TODO unit test for the property 'LockoutEnd'
        }
        /// <summary>
        /// Test the property 'LockoutEnabled'
        /// </summary>
        [Test]
        public void LockoutEnabledTest()
        {
            // TODO unit test for the property 'LockoutEnabled'
        }
        /// <summary>
        /// Test the property 'AccessFailedCount'
        /// </summary>
        [Test]
        public void AccessFailedCountTest()
        {
            // TODO unit test for the property 'AccessFailedCount'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }

    }

}
