/* 
 * AspApiSample.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserPasswordForgotResource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserPasswordForgotResourceTests
    {
        // TODO uncomment below to declare an instance variable for UserPasswordForgotResource
        //private UserPasswordForgotResource instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserPasswordForgotResource
            //instance = new UserPasswordForgotResource();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserPasswordForgotResource
        /// </summary>
        [Test]
        public void UserPasswordForgotResourceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserPasswordForgotResource
            //Assert.IsInstanceOfType<UserPasswordForgotResource> (instance, "variable 'instance' is a UserPasswordForgotResource");
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

    }

}
