/* 
 * AspApiSample.Web.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserSignInResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserSignInResponseTests
    {
        // TODO uncomment below to declare an instance variable for UserSignInResponse
        //private UserSignInResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserSignInResponse
            //instance = new UserSignInResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserSignInResponse
        /// </summary>
        [Test]
        public void UserSignInResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserSignInResponse
            //Assert.IsInstanceOfType<UserSignInResponse> (instance, "variable 'instance' is a UserSignInResponse");
        }


        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Test]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Test]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }

    }

}
