/* 
 * AspApiSample.Web.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserGetUsersResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserGetUsersResponseTests
    {
        // TODO uncomment below to declare an instance variable for UserGetUsersResponse
        //private UserGetUsersResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserGetUsersResponse
            //instance = new UserGetUsersResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserGetUsersResponse
        /// </summary>
        [Test]
        public void UserGetUsersResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserGetUsersResponse
            //Assert.IsInstanceOfType<UserGetUsersResponse> (instance, "variable 'instance' is a UserGetUsersResponse");
        }


        /// <summary>
        /// Test the property 'Users'
        /// </summary>
        [Test]
        public void UsersTest()
        {
            // TODO unit test for the property 'Users'
        }

    }

}
