/* 
 * AspApiSample.Web.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AdminApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AdminApiTests
    {
        private AdminApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AdminApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AdminApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AdminApi
            //Assert.IsInstanceOfType(typeof(AdminApi), instance, "instance is a AdminApi");
        }

        /// <summary>
        /// Test ApiAdminRoleRoleNameGet
        /// </summary>
        [Test]
        public void ApiAdminRoleRoleNameGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string roleName = null;
            //var response = instance.ApiAdminRoleRoleNameGet(roleName);
            //Assert.IsInstanceOf<RoleGetRoleResponse> (response, "response is RoleGetRoleResponse");
        }
        /// <summary>
        /// Test ApiAdminRolesCreatePost
        /// </summary>
        [Test]
        public void ApiAdminRolesCreatePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RoleCreateResource body = null;
            //instance.ApiAdminRolesCreatePost(body);
            
        }
        /// <summary>
        /// Test ApiAdminRolesDeleteRoleNameDelete
        /// </summary>
        [Test]
        public void ApiAdminRolesDeleteRoleNameDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string roleName = null;
            //instance.ApiAdminRolesDeleteRoleNameDelete(roleName);
            
        }
        /// <summary>
        /// Test ApiAdminRolesGet
        /// </summary>
        [Test]
        public void ApiAdminRolesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiAdminRolesGet();
            //Assert.IsInstanceOf<RoleGetRolesResponse> (response, "response is RoleGetRolesResponse");
        }
        /// <summary>
        /// Test ApiAdminUserUserEmailGet
        /// </summary>
        [Test]
        public void ApiAdminUserUserEmailGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userEmail = null;
            //var response = instance.ApiAdminUserUserEmailGet(userEmail);
            //Assert.IsInstanceOf<UserGetUserResponse> (response, "response is UserGetUserResponse");
        }
        /// <summary>
        /// Test ApiAdminUserUserEmailRolesPost
        /// </summary>
        [Test]
        public void ApiAdminUserUserEmailRolesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userEmail = null;
            //RoleAddUserResource body = null;
            //instance.ApiAdminUserUserEmailRolesPost(userEmail, body);
            
        }
        /// <summary>
        /// Test ApiAdminUsersDeleteUserNameDelete
        /// </summary>
        [Test]
        public void ApiAdminUsersDeleteUserNameDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userName = null;
            //instance.ApiAdminUsersDeleteUserNameDelete(userName);
            
        }
        /// <summary>
        /// Test ApiAdminUsersGet
        /// </summary>
        [Test]
        public void ApiAdminUsersGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiAdminUsersGet();
            //Assert.IsInstanceOf<UserGetUsersResponse> (response, "response is UserGetUsersResponse");
        }
    }

}
