/* 
 * AspApiSample.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AuthApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AuthApiTests
    {
        private AuthApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AuthApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AuthApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AuthApi
            //Assert.IsInstanceOfType(typeof(AuthApi), instance, "instance is a AuthApi");
        }

        /// <summary>
        /// Test ApiAuthRolesPost
        /// </summary>
        [Test]
        public void ApiAuthRolesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RoleCreateResource body = null;
            //instance.ApiAuthRolesPost(body);
            
        }
        /// <summary>
        /// Test ApiAuthUserChangePasswordPut
        /// </summary>
        [Test]
        public void ApiAuthUserChangePasswordPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UserPasswordChangeResource body = null;
            //instance.ApiAuthUserChangePasswordPut(body);
            
        }
        /// <summary>
        /// Test ApiAuthUserForgotPasswordPost
        /// </summary>
        [Test]
        public void ApiAuthUserForgotPasswordPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UserPasswordForgotResource body = null;
            //instance.ApiAuthUserForgotPasswordPost(body);
            
        }
        /// <summary>
        /// Test ApiAuthUserResetPasswordPost
        /// </summary>
        [Test]
        public void ApiAuthUserResetPasswordPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UserPasswordResetResource body = null;
            //instance.ApiAuthUserResetPasswordPost(body);
            
        }
        /// <summary>
        /// Test ApiAuthUserSignInPost
        /// </summary>
        [Test]
        public void ApiAuthUserSignInPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UserSignInResource body = null;
            //instance.ApiAuthUserSignInPost(body);
            
        }
        /// <summary>
        /// Test ApiAuthUserSignUpConfirmGet
        /// </summary>
        [Test]
        public void ApiAuthUserSignUpConfirmGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //string email = null;
            //instance.ApiAuthUserSignUpConfirmGet(token, email);
            
        }
        /// <summary>
        /// Test ApiAuthUserSignUpPost
        /// </summary>
        [Test]
        public void ApiAuthUserSignUpPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UserSignUpResource body = null;
            //var response = instance.ApiAuthUserSignUpPost(body);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test ApiAuthUserUserEmailRolesPost
        /// </summary>
        [Test]
        public void ApiAuthUserUserEmailRolesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string userEmail = null;
            //RoleAddUserResource body = null;
            //instance.ApiAuthUserUserEmailRolesPost(userEmail, body);
            
        }
    }

}
